#22: Updated version to 0.32.0, added stack size
objectionary/eo-json pull request #23
Opened 2023-10-17 16:17 UTC by levBagryansky

Closes #22 
I added `stack-size` because rultor cannot merge it due to stack-overflow

2023-10-18 12:32 UTC, levBagryansky commented
I use v4-beta according to https://github.com/codecov/codecov-action/issues/1089 and https://github.com/codecov/codecov-action/issues/1091

2023-10-18 12:33 UTC, levBagryansky commented
@Graur please take a look

2023-10-18 12:43 UTC, Graur requested changes

2023-10-18 12:43 UTC, Graur commented on pom.xml
> +              junit.jupiter.execution.parallel.mode.default = concurrent
@levBagryansky Do we really need to execute this project's tests in paralell?

2023-10-18 13:58 UTC, Graur commented on pom.xml
> +              junit.jupiter.execution.parallel.mode.default = concurrent
@levBagryansky Do you mean 8 minutes without parallell execution?

2023-10-18 14:32 UTC, levBagryansky commented on pom.xml
> +              junit.jupiter.execution.parallel.mode.default = concurrent
@Graur yes. Also it is already enabled in eo repository

2023-10-19 07:59 UTC, Graur commented on pom.xml
> +              junit.jupiter.execution.parallel.mode.default = concurrent
@levBagryansky Did you try to run it without concurrent execution?

2023-10-19 10:31 UTC, levBagryansky commented on pom.xml
> +              junit.jupiter.execution.parallel.mode.default = concurrent
@Graur I measured again and parallel testing takes `08:22` min but sequential testing takes `10:20 min.`

2023-10-19 11:07 UTC, Graur approved these changes

2023-10-19 11:25 UTC, levBagryansky commented
@yegor256 please take a look

2023-10-19 14:23 UTC, yegor256 commented
@rultor merge

2023-10-19 14:27 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/35766-1771098433)

2023-10-19 14:45 UTC, merged

2023-10-19 14:46 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/35766-1771098433) (took me 19min)